### ISSUE TITLE
PHP Path

### ISSUE THREAD

**Issue by FatBoyXPC** [kristijanhusak/deoplete-phpactor#1]
I seem to have issues when using this with php5 but not php7. I know that phpactor lets me set the php bin path that I want to use. Does [this line](https://github.com/kristijanhusak/deoplete-phpactor/blob/5d43c03dd1ee8c49979558ef8f290d1d9dddfafd/rplugin/python3/deoplete/source/phpactor.py#L41) say to use the php found in your path? If so, can we use phpactor's `g:phpactorPhpBin` instead?

**Comment by kristijanhusak** [comment]
Does phpactor even support anything below php 7? According to [requirements](https://github.com/phpactor/phpactor#requirements) it does not.

But yeah, we need to `g:phpactorPhpBin` just in case. I'll fix it.

**Comment by FatBoyXPC** [comment]
PR incoming, actually! I'm just unsure why my vim has `g:phpactorPhpBin` defined as `/usr/bin/php` when I've removed that setting from my vimrc :(

phpactor only supports php7, so I specifically set that variable to the php7 bin so I can use it within my php5 projects :smile:
