### ISSUE TITLE
Sort results

### ISSUE THREAD

**Issue by joereynolds** [kristijanhusak/deoplete-phpactor#3]
The results from this plugin aren't in any particular order, it's not a huge deal but padawan sorts them so it's easier to navigate.

(See below where completions are coming from both phpactor and padawan)

![image](https://user-images.githubusercontent.com/9536682/42152575-71461642-7dd8-11e8-88df-b45495016757.png)

**Comment by kristijanhusak** [comment]
Results are shown in order as they appear from the phpactor rpc, so maybe there should be a sorting option on that level.

**Comment by kristijanhusak** [comment]
@dantleech, is something like this easily implementable into phpactor easily?

If not, i can add an option to sort them on the python level.

**Comment by dantleech** [comment]
I think we could sort them at Phactor level, would make sense for all plugins I think

**Comment by dantleech** [comment]
In fact, probably as easy as adding $suggestions->sorted() here: 
 https://github.com/phpactor/phpactor/blob/648b1288bb0c68cfc6bb86b262eb4b6e773c25af/lib/Extension/Completion/Application/Complete.php#L24.php

**Comment by kristijanhusak** [comment]
Ok, great, then we can move this issue to phpactor repo then.

**Comment by dantleech** [comment]
https://github.com/phpactor/phpactor/pull/516
